repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
      - id: check-json
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-ast
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.9.2'
    hooks:
    -   id: isort
