schema = {
    "doc": "Motion reading.",
    "name": "Motion",
    "namespace": "F12020",
    "type": "record",
    "fields": [
        {"name": "type", "type": "string"},
        {"name": "name", "type": "string"},
        {"name": "sessionTime", "type": "float"},
        {"name": "sessionUID", "type": "double"},
        {"name": "worldPositionX", "type": "float"},
        {"name": "worldPositionY", "type": "float"},
        {"name": "worldPositionZ", "type": "float"},
        {"name": "worldVelocityX", "type": "float"},
        {"name": "worldVelocityY", "type": "float"},
        {"name": "worldVelocityZ", "type": "float"},
        {"name": "worldForwardDirX", "type": "int"},
        {"name": "worldForwardDirY", "type": "int"},
        {"name": "worldForwardDirZ", "type": "int"},
        {"name": "worldRightDirX", "type": "int"},
        {"name": "worldRightDirY", "type": "int"},
        {"name": "worldRightDirZ", "type": "int"},
        {"name": "gForceLateral", "type": "float"},
        {"name": "gForceLongitudinal", "type": "float"},
        {"name": "gForceVertical", "type": "float"},
        {"name": "yaw", "type": "float"},
        {"name": "pitch", "type": "float"},
        {"name": "roll", "type": "float"},
        {"name": "localVelocityX", "type": "float"},
        {"name": "localVelocityY", "type": "float"},
        {"name": "localVelocityZ", "type": "float"},
        {"name": "angularVelocityX", "type": "float"},
        {"name": "angularVelocityY", "type": "float"},
        {"name": "angularVelocityZ", "type": "float"},
        {"name": "angularAccelerationX", "type": "float"},
        {"name": "angularAccelerationY", "type": "float"},
        {"name": "angularAccelerationZ", "type": "float"},
        {"name": "frontWheelsAngle", "type": "float"},
    ],
}
