schema = {
    "doc": "Participants reading.",
    "name": "Participants",
    "namespace": "F12020",
    "type": "record",
    "fields": [
        {"name": "type", "type": "string"},
        {"name": "name", "type": "string"},
        {"name": "sessionTime", "type": "float"},
        {"name": "sessionUID", "type": "double"},
        {"name": "teammate", "type": "int"},
        {"name": "team_name", "type": "string"},
        {"name": "numActiveCars", "type": "int"},
        {"name": "aiControlled", "type": "int"},
        {"name": "driverId", "type": "int"},
        {"name": "teamId", "type": "int"},
        {"name": "raceNumber", "type": "int"},
        {"name": "nationality", "type": "int"},
        {"name": "yourTelemetry", "type": "int"},
    ],
}
