schema = {
    "doc": "Session reading.",
    "name": "Session",
    "namespace": "F12020",
    "type": "record",
    "fields": [
        {"name": "type", "type": "string"},
        {"name": "name", "type": "string"},
        {"name": "sessionTime", "type": "float"},
        {"name": "sessionUID", "type": "Double"},
        {"name": "frontWing", "type": "int"},
        {"name": "rearWing", "type": "int"},
        {"name": "onThrottle", "type": "int"},
        {"name": "offThrottle", "type": "int"},
        {"name": "frontCamber", "type": "float"},
        {"name": "rearCamber", "type": "float"},
        {"name": "frontToe", "type": "float"},
        {"name": "rearToe", "type": "float"},
        {"name": "frontSuspension", "type": "int"},
        {"name": "rearSuspension", "type": "int"},
        {"name": "frontAntiRollBar", "type": "int"},
        {"name": "rearAntiRollBar", "type": "int"},
        {"name": "frontSuspensionHeight", "type": "int"},
        {"name": "rearSuspensionHeight", "type": "int"},
        {"name": "brakePressure", "type": "int"},
        {"name": "brakeBias", "type": "int"},
        {"name": "rearLeftTyrePressure", "type": "float"},
        {"name": "rearRightTyrePressure", "type": "float"},
        {"name": "frontLeftTyrePressure", "type": "float"},
        {"name": "frontRightTyrePressure", "type": "float"},
        {"name": "ballast", "type": "int"},
        {"name": "fuelLoad", "type": "float"},
    ],
}
