schema = {
    "doc": "Status of the car reading.",
    "name": "CarStatus",
    "namespace": "F12020",
    "type": "record",
    "fields": [
        {"name": "type", "type": "string"},
        {"name": "name", "type": "string"},
        {"name": "sessionTime", "type": "float"},
        {"name": "sessionUID", "type": "double"},
        {"name": "tractionControl", "type": "int"},
        {"name": "antiLockBrakes", "type": "int"},
        {"name": "fuelMix", "type": "int"},
        {"name": "frontBrakeBias", "type": "int"},
        {"name": "pitLimiterStatus", "type": "int"},
        {"name": "fuelInTank", "type": "float"},
        {"name": "fuelCapacity", "type": "float"},
        {"name": "fuelRemainingLaps", "type": "float"},
        {"name": "maxRPM", "type": "int"},
        {"name": "idleRPM", "type": "int"},
        {"name": "maxGears", "type": "int"},
        {"name": "drsAllowed", "type": "int"},
        {"name": "drsActivationDistance", "type": "int"},
        {"name": "tyresWear_rl", "type": "int"},
        {"name": "tyresWear_rr", "type": "int"},
        {"name": "tyresWear_fl", "type": "int"},
        {"name": "tyresWear_fr", "type": "int"},
        {"name": "actualTyreCompound", "type": "int"},
        {"name": "visualTyreCompound", "type": "int"},
        {"name": "tyresAgeLaps", "type": "int"},
        {"name": "tyresDamage_rl", "type": "int"},
        {"name": "tyresDamage_rr", "type": "int"},
        {"name": "tyresDamage_fl", "type": "int"},
        {"name": "tyresDamage_fr", "type": "int"},
        {"name": "frontLeftWingDamage", "type": "int"},
        {"name": "frontRightWingDamage", "type": "int"},
        {"name": "rearWingDamage", "type": "int"},
        {"name": "drsFault", "type": "int"},
        {"name": "engineDamage", "type": "int"},
        {"name": "gearBoxDamage", "type": "int"},
        {"name": "vehicleFiaFlags", "type": "int"},
        {"name": "ersStoreEnergy", "type": "float"},
        {"name": "ersDeployMode", "type": "int"},
        {"name": "ersHarvestedThisLapMGUK", "type": "float"},
        {"name": "ersHarvestedThisLapMGUH", "type": "float"},
        {"name": "ersDeployedThisLap", "type": "float"},
    ],
}
