schema = {
    "doc": "Telemetry reading.",
    "name": "Telemetry",
    "namespace": "F12020",
    "type": "record",
    "fields": [
        {"name": "type", "type": "string"},
        {"name": "name", "type": "string"},
        {"name": "sessionTime", "type": "float"},
        {"name": "sessionUID", "type": "double"},
        {"name": "speed", "type": "int"},
        {"name": "throttle", "type": "float"},
        {"name": "steer", "type": "float"},
        {"name": "brake", "type": "float"},
        {"name": "clutch", "type": "int"},
        {"name": "gear", "type": "int"},
        {"name": "engineRPM", "type": "int"},
        {"name": "drs", "type": "int"},
        {"name": "revLightsPercent", "type": "int"},
        {"name": "brakesTemperature_rl", "type": "int"},
        {"name": "brakesTemperature_rr", "type": "int"},
        {"name": "brakesTemperature_fl", "type": "int"},
        {"name": "brakesTemperature_fr", "type": "int"},
        {"name": "tyresSurfaceTemperature_rl", "type": "int"},
        {"name": "tyresSurfaceTemperature_rr", "type": "int"},
        {"name": "tyresSurfaceTemperature_fl", "type": "int"},
        {"name": "tyresSurfaceTemperature_fr", "type": "int"},
        {"name": "tyresInnerTemperature_rl", "type": "int"},
        {"name": "tyresInnerTemperature_rr", "type": "int"},
        {"name": "tyresInnerTemperature_fl", "type": "int"},
        {"name": "tyresInnerTemperature_fr", "type": "int"},
        {"name": "engineTemperature", "type": "int"},
        {"name": "tyresPressure_rl", "type": "float"},
        {"name": "tyresPressure_rr", "type": "float"},
        {"name": "tyresPressure_fl", "type": "float"},
        {"name": "tyresPressure_fr", "type": "float"},
        {"name": "surfaceType_rl", "type": "int"},
        {"name": "surfaceType_rr", "type": "int"},
        {"name": "surfaceType_fl", "type": "int"},
        {"name": "surfaceType_fr", "type": "int"},
        {"name": "buttonStatus", "type": "int"},
        {"name": "mfdPanelIndex", "type": "int"},
        {"name": "mfdPanelIndexSecondaryPlayer", "type": "int"},
        {"name": "suggestedGear", "type": "int"},
    ],
}
